#!/bin/bash
# ftrcit 
# trace-cmd wrapper script..
[ $(id -u) -ne 0 ] && {
 echo "$0: need to be root"
 exit 1
}

KMOD=mmap_baddrv
echo "[+] ftrace reset ..."
trace-cmd reset

# Filters
echo "[+] Setting up ftrace filters ..."
echo ":mod:${KMOD}" >> /sys/kernel/debug/tracing/set_ftrace_filter 
echo "*mmap*" >> /sys/kernel/debug/tracing/set_ftrace_filter
echo "*vma*" >> /sys/kernel/debug/tracing/set_ftrace_filter

./load_drv.sh -c ./${KMOD}.ko || exit 1

echo "[+] trace-cmd: recording ..."
#trace-cmd record -p function_graph -e kmem -e oom -e mod -F taskset 01 insmod ./${KMOD}.ko
trace-cmd record -p function_graph -e syscalls -e kmem -e oom -e mod -F ./userspc_mmap /dev/mmap_baddrv 20000
echo "[+] trace-cmd: report gen..."

REP=ftrc_report
trace-cmd report -I -S -l > ${REP}  #ftrc_report_$(date +%a_%d_%m_%Y_%H%M).txt
ls -lh ${REP}

echo "[+] Unloading module $KMOD..."
rmmod ${KMOD}
echo "[+] ftrace reset ..."
trace-cmd reset
