version: '2'

services:
  checksec-ubuntu:
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu
    image: checksec-ubuntu
    command: bash -c "./tests/test-checksec.sh"

  checksec-photon:
    build:
      context: ./
      dockerfile: Dockerfile.photon
    image: checksec-photon
    command: bash -c "./tests/test-checksec.sh"

  shellcheck:
    volumes:
      - .:/mnt
    image: koalaman/shellcheck
    command: "checksec"
