version: '2'

services:
  checksec-ubuntu:
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu
    image:  checksec-ubuntu
    command: bash -c "./tests/test-checksec.sh"

  checksec-arch:
    build:
      context: ./
      dockerfile: Dockerfile.arch
    image:  checksec-arch
    command: bash -c "./tests/test-checksec.sh"
